
如果任何一个`AsyncHook`回调抛出，应用程序将会打印堆栈跟踪并退出。退出路径确实遵循一个未捕获的异常，但是所有的`uncaughtException`监听器都被删除，因此强迫进程退出。`'exit'`回调还会被调用除非应用程序使用`--abort-on-uncaught-exception`运行，在这种情况下，将会打印堆栈跟踪并退出程序，留下一个核心文件。

产生这种错误处理行为的原因是这些回调运行在对象的生命周期中的潜在易变点上，例如类构造和销毁期间。 因此，为了防止之后的无意中止，有必要快结束这一进程。 如果进行综合分析后可以确保异常将会遵循正常的控制流程而没有无意的负面影响，那么之后也可能会发生变化。

